all:
	make --directory=bfs
	make --directory=fft
	make --directory=gemm
	make --directory=md
	make --directory=scan
	make --directory=sort
	make --directory=stencil
	make --directory=triad

clean:
	rm -rf bin
