#!/usr/bin/env python
import os
import sys

PYTHIA_HOME=os.path.dirname(os.path.realpath(__file__))+"/.."


def main(argv):
    compile_cmd="DEC++ -spp " + PYTHIA_HOME + "/pass/preproc.sh"
    dec_args=""
    for arg in argv[1:]:
        dec_args=dec_args+" "+arg

    final_cmd=compile_cmd+dec_args
    print(final_cmd)
    
    os.system(final_cmd)
    #print(PYTHIA_HOME)
    
if __name__=="__main__":
    main(sys.argv)


