#!/usr/bin/env python

#wrapper around DEC++ and -spp preproc.sh
#intended to be used just like a DEC++ call, without having to use additional flags
#automatically adds flag -spp /path/to/preproc.sh

import os
import sys

PYTHIA_HOME=os.path.dirname(os.path.realpath(os.path.realpath(__file__)+"/.."))

def main(argv):
    print("Pythia Home: "+PYTHIA_HOME)    
    compile_cmd="DEC++ -spp " + PYTHIA_HOME + "/pass/preproc.sh --target simulator"
    dec_args=""
    for arg in argv[1:]:
        dec_args=dec_args+" "+arg

    final_cmd=compile_cmd+dec_args
    print(final_cmd)
    
    os.system(final_cmd)
    
    
if __name__=="__main__":
    main(sys.argv)


