#!/usr/bin/env python

import os
import sys
import argparse


PYTHIA_HOME=os.path.dirname(os.path.realpath(os.path.realpath(__file__)+"/.."))
PYTHIA_BIN=PYTHIA_HOME+"/bin"


def main():
    parser = argparse.ArgumentParser()    
    parser.add_argument('source_directory',  nargs=1, help="Source directory containing decades_base or decades_decoupled_inplicit folders")
    parser.add_argument("-sc","--sim_config",type=str,help="Config mode for simulator, shared L2, and DRAM. \n Options: sim_default", default="sim_default")
    parser.add_argument("-cc","--core_config",type=str,help="Config mode for cores and their private L1s. \n Options: core_inorder, core_ooo, core_inorder_perfcache, core_ooo_perfcache, core_accel", default="core_inorder")
    parser.add_argument("-n", "--num_cores", type=int, help="Number of cores to run with",default=1)
    parser.add_argument("-d", "--decoupled", help="Flag to run in decoupled Supply/Compute mode", action='store_true')
    parser.add_argument("-v", "--verbose", help="Flag to run in verbose mode", action='store_true')
    parser.add_argument("-o", "--output", type=str, help="Output file for Pythia run statistics (default is stdout)")
    args=parser.parse_args()
    numcores=args.num_cores
    #print(args.source_directory)
    cmd=""
    pythia_numcores=numcores

    source_directory=os.path.realpath(args.source_directory[0])
    core_config_path=PYTHIA_HOME+"/sim/config/"+args.core_config+".txt"
    sim_config_path=PYTHIA_HOME+"/sim/config/"+args.sim_config+".txt"

    decoupled_path=source_directory+"/decades_decoupled_implicit"
    base_path=source_directory+"/decades_base"
    home_path=base_path
    if args.decoupled:
        pythia_numcores=2*numcores
        home_path=decoupled_path
        
    cmd = PYTHIA_BIN+"/sim -n "+str(pythia_numcores)+" "+sim_config_path
    
    #loop through number of threads collecting args
    for i in range(numcores):
        compute_path=home_path+"/output_compute_"+str(i)
        supply_path=home_path+"/output_supply_"+str(i+numcores)
        cmd=cmd+" "+compute_path +" "+core_config_path
        if args.decoupled:
            cmd=cmd+" "+supply_path +" "+core_config_path

    if args.verbose:
        cmd=cmd+" -v"
    if args.output is not None:
        cmd=cmd+" > "+args.output

    

    print(cmd)
    os.system(cmd)
    
if __name__=="__main__":
    main()
